const defaultTheme = require('tailwindcss/defaultTheme')
const path = require('path')

module.exports = {
  content: [
    './public/*.html',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
    './app/views/**/*.{erb,haml,html,slim}',
    // File della gemma BetterUI
    '../../app/views/**/*.{erb,haml,html,slim}',
    '../../app/helpers/**/*.rb',
    '../../app/components/**/*.{rb,erb}'
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/container-queries'),
  ],
  safelist: [
    // Classi base dei bottoni
    'better-ui-button',
    'inline-flex',
    'items-center',
    'justify-center',
    'rounded-md',
    'font-medium',
    'transition-colors',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    'focus:ring-blue-500',
    'w-full',
    // Classi per i tipi di bottoni
    'bg-blue-600',
    'hover:bg-blue-700',
    'text-white',
    'bg-gray-200',
    'hover:bg-gray-300',
    'text-gray-800',
    'bg-green-600',
    'hover:bg-green-700',
    'bg-red-600',
    'hover:bg-red-700',
    'bg-yellow-500',
    'hover:bg-yellow-600',
    'bg-sky-500',
    'hover:bg-sky-600',
    'bg-white',
    'hover:bg-gray-100',
    'border',
    'border-gray-300',
    'bg-gray-800',
    'hover:bg-gray-900',
    // Outline buttons
    'bg-transparent',
    'text-blue-600',
    'border-blue-600',
    'hover:text-white',
    'hover:bg-blue-600',
    'text-green-600',
    'border-green-600',
    'hover:bg-green-600',
    'text-red-600',
    'border-red-600',
    'hover:bg-red-600',
    // Dimensioni
    'py-1',
    'px-2',
    'text-sm',
    'py-2',
    'px-4',
    'text-base',
    'py-3',
    'px-6',
    'text-lg',
    // Icone
    'mr-2',
    'ml-2',
    // Classi per Font Awesome
    'fas',
    'far',
    'fal',
    'fab',
    'fad',
    'fa-xs',
    'fa-sm',
    'fa-lg',
    'fa-xl',
    'fa-2xl',
    'fa-fw',
    'fa-spin',
    'fa-pulse',
    'fa-border',
    // Icone comunemente usate
    'fa-download',
    'fa-arrow-right',
    'fa-arrow-left',
    'fa-check',
    'fa-times',
    'fa-exclamation',
    'fa-info',
    'fa-user',
    'fa-cog',
    'fa-trash'
  ],
}
